package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"flux-waf/internal/models"
)

// FLUXDLPInspectionPath is the generated body-access + limits file (included early from coraza.conf).
func FLUXDLPInspectionPath() string {
	if p := os.Getenv("FLUX_DLP_INSPECTION_PATH"); p != "" {
		return p
	}
	return "/etc/nginx/coraza/custom/flux_dlp_inspection.conf"
}

// FLUXDLPRulesPath is the generated DLP SecRules file.
func FLUXDLPRulesPath() string {
	if p := os.Getenv("FLUX_DLP_RULES_PATH"); p != "" {
		return p
	}
	return "/etc/nginx/coraza/custom/dlp-rules.conf"
}

// WriteDLPConfigFiles writes inspection limits + DLP rules from dashboard config.
func WriteDLPConfigFiles(cfg models.DLPConfig) error {
	if err := writeDLPInspection(cfg); err != nil {
		return err
	}
	return writeDLPRules(cfg)
}

func writeDLPInspection(cfg models.DLPConfig) error {
	path := FLUXDLPInspectionPath()
	kb := cfg.MaxBodySizeKB
	if kb < 64 {
		kb = 64
	}
	bodyLimit := int64(kb) * 1024
	if bodyLimit > 536870912 { // 512 MiB
		bodyLimit = 536870912
	}
	noFiles := int64(131072)
	if bodyLimit < noFiles {
		noFiles = bodyLimit / 4
		if noFiles < 4096 {
			noFiles = 4096
		}
	}

	req := "Off"
	if cfg.InspectRequestBody {
		req = "On"
	}
	resp := "Off"
	if cfg.InspectResponseBody {
		resp = "On"
	}

	var b strings.Builder
	b.WriteString("# ==============================================================================\n")
	b.WriteString("# Request / response body inspection — generated by Flux WAF (Data Guard)\n")
	b.WriteString("# ==============================================================================\n\n")
	b.WriteString(fmt.Sprintf("SecRequestBodyAccess %s\n", req))
	b.WriteString(fmt.Sprintf("SecRequestBodyLimit %d\n", bodyLimit))
	b.WriteString(fmt.Sprintf("SecRequestBodyNoFilesLimit %d\n", noFiles))
	b.WriteString("SecRequestBodyLimitAction ProcessPartial\n\n")
	b.WriteString(fmt.Sprintf("SecResponseBodyAccess %s\n", resp))
	b.WriteString(fmt.Sprintf("SecResponseBodyLimit %d\n", bodyLimit))
	b.WriteString("SecResponseBodyLimitAction ProcessPartial\n")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("dlp inspection mkdir: %w", err)
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writeDLPRules(cfg models.DLPConfig) error {
	path := FLUXDLPRulesPath()
	var b strings.Builder
	b.WriteString("# ==============================================================================\n")
	b.WriteString("# DLP / Data Guard — generated by Flux WAF (Data Guard)\n")
	b.WriteString("# ID range: 9810xxx\n")
	b.WriteString("# ==============================================================================\n\n")

	if !cfg.DLPEnabled || !cfg.DLPActive {
		b.WriteString("# DLP disabled or inactive — no SecRules.\n")
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return fmt.Errorf("dlp rules mkdir: %w", err)
		}
		return os.WriteFile(path, []byte(b.String()), 0644)
	}

	logDeny := "log"
	logPass := "log"
	if !cfg.AlertOnBlock {
		logDeny = "nolog"
		logPass = "nolog"
	}

	type rule struct {
		deny   bool
		logTok string
		id     string
		rx     string
		msg    string
		sev    string
	}
	rules := []rule{
		{true, logDeny, "9810100", `\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12})\b`, "DLP: Credit Card Number detected", "CRITICAL"},
		{true, logDeny, "9810200", `\b(?:[1-8][0-9]{2}|9(?:[0-8][0-9]|9[0-9]))-(?:[1-9][0-9]|0[1-9])-(?:[1-9][0-9]{3}|0[1-9][0-9]{2}|00[1-9][0-9]|000[1-9])\b`, "DLP: Social Security Number detected", "CRITICAL"},
		{true, logDeny, "9810500", `(?i)(?:api[_\-]?key|bearer|access[_\-]?token|secret)[^\S\n]*[:=][^\S\n]*[A-Za-z0-9\-_.~+/]{16,64}`, "DLP: API Key / Bearer Token detected", "CRITICAL"},
		{true, logDeny, "9810700", `AKIA[0-9A-Z]{16}`, "DLP: AWS Access Key detected", "CRITICAL"},
		{true, logDeny, "9810800", `-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----`, "DLP: Private Key (PEM) detected", "CRITICAL"},
		{false, logPass, "9810600", `(?i)\x22(?:password|passwd|pwd|secret)\x22\s*:\s*\x22[^\x22]{4,}\x22`, "DLP: Password field in payload (audit only)", "ERROR"},
		{false, logPass, "9810900", `eyJ[A-Za-z0-9\-_]{10,}\.eyJ[A-Za-z0-9\-_]{10,}\.[A-Za-z0-9\-_.+/]{10,}`, "DLP: JWT Token in body (audit only)", "ERROR"},
	}

	for _, r := range rules {
		var line string
		if r.deny {
			line = fmt.Sprintf(
				`SecRule REQUEST_BODY "@rx %s" "id:%s,phase:2,deny,status:403,%s,t:none,msg:'%s',tag:'dlp',severity:'%s'"`,
				r.rx, r.id, r.logTok, r.msg, r.sev,
			)
		} else {
			line = fmt.Sprintf(
				`SecRule REQUEST_BODY "@rx %s" "id:%s,phase:2,pass,%s,t:none,msg:'%s',tag:'dlp',severity:'%s'"`,
				r.rx, r.id, r.logTok, r.msg, r.sev,
			)
		}
		b.WriteString(line)
		b.WriteString("\n\n")
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("dlp rules mkdir: %w", err)
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}
